import React, { useEffect, useMemo, useRef, useState } from "react";
import AppModal from "../../common/AppModal";
import { controlsByEventType } from "../utils/specializedScoringUi";
import { BOXING_SCORE_PRESETS, buildBoxingCornerPayload, buildBoxingScorecardRows, resolveBoxingRules, submitBoxingRoundSequentially } from "./boxingScorecardModel.js";

const buttonClass = "min-h-10 rounded-lg border border-[var(--border-soft)] bg-[var(--surface)] px-3 text-sm font-semibold transition hover:bg-[var(--surface-muted)] disabled:cursor-not-allowed disabled:opacity-45";
const selectClass = "min-h-10 rounded-lg border border-[var(--border-soft)] bg-[var(--surface)] px-3 text-sm text-[var(--text-main)]";
const participantName = (participant) => participant?.activePlayers?.[0]?.name || participant?.label || "Awaiting participant";

function Corner({ corner, participant, boxing, controls, disabled, onEvent }) {
  const id = participant?.teamId;
  const accent = corner === "Red" ? "border-red-400/60 bg-red-500/5" : "border-blue-400/60 bg-blue-500/5";
  const badge = corner === "Red" ? "bg-red-600" : "bg-blue-600";
  return <section className={`min-w-0 border-t-2 p-3 sm:p-4 ${accent}`} aria-label={`${corner} Corner ${participantName(participant)}`}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-black uppercase tracking-wide text-white ${badge}`}>{corner} Corner</span><h2 className="mt-2 truncate text-base font-bold sm:text-lg">{participantName(participant)}</h2>{participant?.activePlayers?.[0]?.name && participant?.label ? <p className="truncate text-xs text-[var(--text-muted)]">{participant.label}</p> : null}</div><dl className="text-center text-xs"><dt className="text-[var(--text-muted)]">Warnings</dt><dd className="mt-1 text-lg font-bold">{Number(boxing?.warnings?.[String(id)] || 0)}</dd></dl></div>
    <div className="mt-3 flex flex-wrap gap-2" aria-label={`${corner} Corner actions`}>
      {controls.has("WARNING") ? <button type="button" className={buttonClass} disabled={disabled || !id} aria-label={`Record warning for ${corner} Corner ${participantName(participant)}`} onClick={() => onEvent(buildBoxingCornerPayload({ eventType: "WARNING", participant }))}>Warning {corner}</button> : null}
      {controls.has("CAUTION") || controls.has("KNOCKDOWN") ? <details><summary className={`${buttonClass} flex cursor-pointer list-none items-center`}>More</summary><div className="mt-1 flex flex-wrap gap-1.5">{controls.has("KNOCKDOWN") ? <button type="button" className={buttonClass} disabled={disabled || !id} aria-label={`Record knockdown for ${corner} Corner ${participantName(participant)}`} onClick={() => onEvent(buildBoxingCornerPayload({ eventType: "KNOCKDOWN", participant }))}>Knockdown</button> : null}{controls.has("CAUTION") ? <button type="button" className={buttonClass} disabled={disabled || !id} aria-label={`Record caution for ${corner} Corner ${participantName(participant)}`} onClick={() => onEvent(buildBoxingCornerPayload({ eventType: "CAUTION", participant }))}>Caution</button> : null}</div></details> : null}
    </div>
  </section>;
}

export default function BoxingScorecardSurface({ config, liveState, participants = [], canWrite, isSubmitting, blockingMessage, onSubmitEvent }) {
  const controls = useMemo(() => controlsByEventType(config), [config]);
  const rules = useMemo(() => resolveBoxingRules(config), [config]);
  const boxing = liveState?.boxing_state || {};
  const currentRound = Math.min(Math.max(Number(boxing.current_round || 1), 1), rules.rounds);
  const red = participants[0]; const blue = participants[1];
  const accepted = boxing?.scorecards?.[String(currentRound)] || {};
  const roundComplete = Object.keys(accepted).length === rules.judgeCount;
  const dqTarget = Number(boxing.disqualification_required_for || 0);
  const tieJudges = Array.isArray(boxing.tie_break_required) ? boxing.tie_break_required : [];
  const [cards, setCards] = useState({}); const [submissionError, setSubmissionError] = useState(""); const [isSubmittingRound, setIsSubmittingRound] = useState(false);
  const [stoppageOpen, setStoppageOpen] = useState(false); const [stoppageWinner, setStoppageWinner] = useState(""); const [stoppageType, setStoppageType] = useState(""); const [tieNominations, setTieNominations] = useState({});
  const confirmRef = useRef(null);
  const disabled = !canWrite || isSubmitting || isSubmittingRound || Boolean(blockingMessage);
  const stoppages = [["KNOCKOUT", "Knockout"], ["REFEREE_STOPPAGE", "Referee stoppage"], ["DISQUALIFICATION", "Disqualification"]].filter(([type]) => controls.has(type));
  useEffect(() => { const next = {}; for (let judge = 1; judge <= rules.judgeCount; judge += 1) { const saved = accepted[String(judge)]; next[judge] = saved ? { red: Number(saved[String(red?.teamId)]), blue: Number(saved[String(blue?.teamId)]) } : null; } setCards(next); setSubmissionError(""); }, [boxing?.scorecards, blue?.teamId, currentRound, red?.teamId, rules.judgeCount]);
  const submitRound = async () => { setIsSubmittingRound(true); setSubmissionError(""); try { const result = await submitBoxingRoundSequentially({ cards, acceptedCards: accepted, judgeCount: rules.judgeCount, round: currentRound, rounds: rules.rounds, redId: red?.teamId, blueId: blue?.teamId, submit: onSubmitEvent }); if (!result.ok) setSubmissionError(result.error); } finally { setIsSubmittingRound(false); } };
  const rows = buildBoxingScorecardRows({ scorecards: boxing.scorecards, judgeCount: rules.judgeCount, rounds: rules.rounds, redId: red?.teamId, blueId: blue?.teamId });
  const openStoppage = (type = stoppages[0]?.[0] || "KNOCKOUT", winner = "") => { setStoppageType(type); setStoppageWinner(String(winner || "")); setStoppageOpen(true); };
  return <div className="space-y-3">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[var(--border-soft)] px-1 pb-2"><p className="font-semibold">Round {currentRound} of {rules.rounds}</p><p className="text-xs text-[var(--text-muted)]">{rules.judgeCount} judges · {rules.scoringSystem.toLowerCase()}{rules.roundDurationMinutes ? ` · ${rules.roundDurationMinutes} min rounds` : ""}</p></div>
    <div className="grid gap-3 md:grid-cols-2"><Corner corner="Red" participant={red} boxing={boxing} controls={controls} disabled={disabled || dqTarget > 0} onEvent={onSubmitEvent}/><Corner corner="Blue" participant={blue} boxing={boxing} controls={controls} disabled={disabled || dqTarget > 0} onEvent={onSubmitEvent}/></div>
    <section className="border-t border-[var(--border-soft)] pt-3" aria-labelledby="boxing-round-scores"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id="boxing-round-scores" className="font-bold">Round {currentRound} Scorecard</h2><span className="text-xs font-bold uppercase tracking-wide text-[var(--text-muted)]">Red - Blue</span></div>
      <div className="mt-3 space-y-2">{Array.from({ length: rules.judgeCount }, (_, i) => i + 1).map((judge) => <div key={judge} className="grid gap-2 border-b border-[var(--border-soft)] pb-2 lg:grid-cols-[90px_minmax(0,1fr)] lg:items-center"><p className="text-sm font-semibold">Judge {judge}{accepted[String(judge)] ? " ✓" : ""}</p><div className="flex flex-wrap gap-1.5" role="group" aria-label={`Judge ${judge} score Red then Blue`}>{BOXING_SCORE_PRESETS.map((preset) => { const selected = cards[judge]?.red === preset.red && cards[judge]?.blue === preset.blue; return <button key={preset.id} type="button" aria-label={`Judge ${judge} score Red ${preset.red} Blue ${preset.blue}`} aria-pressed={selected} disabled={disabled || dqTarget > 0 || Boolean(accepted[String(judge)])} onClick={() => { setCards((value) => ({ ...value, [judge]: { red: preset.red, blue: preset.blue } })); setSubmissionError(""); }} className={`${buttonClass} ${selected ? "border-cyan-600 bg-cyan-50 text-cyan-800 ring-1 ring-cyan-600 dark:bg-cyan-500/15 dark:text-cyan-100" : ""}`}>{preset.id}</button>; })}</div></div>)}</div>
      {submissionError ? <p className="mt-2 text-sm font-semibold text-rose-700 dark:text-rose-200" role="alert">{submissionError}</p> : null}
      <div className="mt-3 flex justify-end">{currentRound === rules.rounds && roundComplete ? <button type="button" className="min-h-11 rounded-lg bg-cyan-600 px-5 text-sm font-bold text-white disabled:opacity-45" disabled={disabled || dqTarget > 0 || !controls.has("OFFICIAL_DECISION")} onClick={() => onSubmitEvent({ event_type: "OFFICIAL_DECISION", metadata: { round: currentRound } })}>Confirm Official Result</button> : <button type="button" className="min-h-11 rounded-lg bg-cyan-600 px-5 text-sm font-bold text-white disabled:opacity-45" disabled={disabled || dqTarget > 0 || !red?.teamId || !blue?.teamId || !controls.has("JUDGE_SCORE_SUBMITTED")} onClick={submitRound}>{isSubmittingRound ? "Submitting…" : currentRound === rules.rounds ? "Submit Final Round" : `Submit Round ${currentRound}`}</button>}</div>
    </section>
    {dqTarget > 0 ? <div className="rounded-lg border border-rose-300 bg-rose-50 p-3 text-sm text-rose-800 dark:border-rose-500/40 dark:bg-rose-500/10 dark:text-rose-100" role="alert"><p className="font-bold">{dqTarget === Number(red?.teamId) ? "Red" : "Blue"} Corner has reached 3 warnings.</p><p>Disqualification must be resolved before scoring can continue.</p><button type="button" className={`${buttonClass} mt-2`} disabled={disabled} onClick={() => openStoppage("DISQUALIFICATION", dqTarget === Number(red?.teamId) ? blue?.teamId : red?.teamId)}>Review Disqualification</button></div> : null}
    {tieJudges.length ? <section className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-500/40 dark:bg-amber-500/10 dark:text-amber-100"><h3 className="font-bold">Tie-break required</h3><p className="mt-1">Each tied judge must nominate the bout winner.</p>{tieJudges.map((judge) => <label key={judge} className="mt-2 grid gap-1 font-semibold">Judge {judge}<select className={selectClass} value={tieNominations[judge] || ""} onChange={(event) => setTieNominations((value) => ({ ...value, [judge]: Number(event.target.value) }))}><option value="">Select winner</option><option value={red?.teamId}>Red Corner · {participantName(red)}</option><option value={blue?.teamId}>Blue Corner · {participantName(blue)}</option></select></label>)}<button type="button" className={`${buttonClass} mt-3`} disabled={disabled || tieJudges.some((judge) => !tieNominations[judge])} onClick={() => onSubmitEvent({ event_type: "OFFICIAL_DECISION", metadata: { round: currentRound, tie_break_nominations: tieNominations } })}>Confirm tie-break result</button></section> : null}
    <div className="flex flex-wrap gap-2 border-t border-[var(--border-soft)] pt-3"><details className="min-w-0 flex-1"><summary className={`${buttonClass} inline-flex cursor-pointer list-none items-center`}>Scorecards</summary><div className="mt-2 max-w-full overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><caption className="sr-only">Official Boxing scorecards by judge and round</caption><thead><tr><th className="p-2">Judge</th>{Array.from({ length: rules.rounds }, (_, i) => <th key={i} className="p-2">R{i + 1}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.judge} className="border-t border-[var(--border-soft)]"><th className="p-2">Judge {row.judge}</th>{row.cards.map((card, i) => <td key={i} className="p-2">{card ? `${card.red}-${card.blue}` : "—"}</td>)}</tr>)}</tbody></table></div></details>{stoppages.length ? <button type="button" className="min-h-10 rounded-lg border border-rose-300 bg-rose-50 px-3 text-sm font-bold text-rose-800 disabled:opacity-45 dark:border-rose-500/40 dark:bg-rose-500/10 dark:text-rose-200" disabled={disabled} aria-label="End Boxing bout" onClick={() => openStoppage()}>End Bout</button> : null}</div>
    <AppModal open={stoppageOpen} onClose={() => setStoppageOpen(false)} title="End bout" subtitle="Confirm the winner and official result." maxWidthClass="max-w-lg" initialFocusRef={confirmRef}><div className="space-y-4"><label className="grid gap-1 text-sm font-semibold">Winner<select className={selectClass} value={stoppageWinner} onChange={(event) => setStoppageWinner(event.target.value)}><option value="">Select winner</option><option value={red?.teamId}>Red Corner · {participantName(red)}</option><option value={blue?.teamId}>Blue Corner · {participantName(blue)}</option></select></label><label className="grid gap-1 text-sm font-semibold">Result<select className={selectClass} value={stoppageType} onChange={(event) => setStoppageType(event.target.value)}>{stoppages.map(([type, label]) => <option key={type} value={type}>{label}</option>)}</select></label><p className="text-sm">Round {currentRound}</p><div className="flex justify-end gap-2"><button type="button" className={buttonClass} onClick={() => setStoppageOpen(false)}>Cancel</button><button ref={confirmRef} type="button" className="min-h-10 rounded-lg bg-rose-600 px-4 text-sm font-bold text-white disabled:opacity-45" disabled={disabled || !stoppageWinner} onClick={async () => { const winner = Number(stoppageWinner) === Number(red?.teamId) ? red : blue; const saved = await onSubmitEvent(buildBoxingCornerPayload({ eventType: stoppageType, participant: winner, metadata: { round: currentRound } })); if (saved !== false) setStoppageOpen(false); }}>Confirm Result</button></div></div></AppModal>
  </div>;
}
